###

GET http://localhost:8080/api/applications/job/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhdHV5aXNoaW1lMjhAZ21haWwuY29tIiwiaWF0IjoxNzg1Mjc3NzMyLCJleHAiOjE3ODUzNjQxMzJ9.zY6opX1gmjunxCBlNox-pevWCZUmexzI6xTsvMLeRBM5NTcf2fAUpByo2IAYhUQ9F96di4IG4gfsJU8fHy9AHg
