spring.application.name=hiresmart-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/HireSmart
spring.datasource.username=postgres
spring.datasource.password=Anne12345


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=hiresmart-dev-secret-key-change-this-before-deploying-to-production-1234567890
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html